/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.FormEmpresaController;
import DAO.conexao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author gdeba
 */
public class CadastroEmpresa extends javax.swing.JFrame {
    private final FormEmpresaController controller;
    
    PreparedStatement statement = null;
    ResultSet rs = null;
    /**
     * Creates new form CadastroEmpresa
     */
    public CadastroEmpresa() throws SQLException {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) jempresas.getModel();
        jempresas.setRowSorter(new TableRowSorter(modelo));
        readJtable();
        controller = new FormEmpresaController(this);
    }
    
    public void readJtable() throws SQLException{
        Connection Conexao = new conexao().getConnection();
        try {
            DefaultTableModel modelo = (DefaultTableModel) jempresas.getModel();
            modelo.setNumRows(0);
            String sql = "select * from empresa";
            statement = Conexao.prepareStatement(sql);
            rs = statement.executeQuery();
            while(rs.next()){
                String id = rs.getString("id");
                String end = rs.getString("endereco");
                String comp = rs.getString("complemento");
                String bairro = rs.getString("bairro");
                String cid = rs.getString("cidade");
                String est = rs.getString("estado");
                String cnpj = rs.getString("cnpj");
                String insc = rs.getString("inscricao_estadual");
                String tel = rs.getString("telefone");
                String num = rs.getString("numero");
                String email = rs.getString("email");
                String nome = rs.getString("nome");
                
                
                
                Object[] obj = {id,nome,end,comp,bairro,num,cid,est,cnpj,insc,tel,email};
                modelo.addRow(obj);
                
            }
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "judcjdsb");
        }
 
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jtxtnome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jcidade = new javax.swing.JTextField();
        jtxtend = new javax.swing.JTextField();
        jtxtcomp = new javax.swing.JTextField();
        jtxtbairro = new javax.swing.JTextField();
        jnum = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jemail = new javax.swing.JTextField();
        jtelefone = new javax.swing.JFormattedTextField();
        jinscricao = new javax.swing.JFormattedTextField();
        jcnpj = new javax.swing.JFormattedTextField();
        jestados = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jempresas = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jtxtid = new javax.swing.JTextField();
        jbtnadd = new javax.swing.JButton();
        jbtnexcludeone = new javax.swing.JButton();
        jbtnexcludeall = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nome");

        jtxtnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtnomeActionPerformed(evt);
            }
        });

        jLabel2.setText("Endereço");

        jLabel3.setText("Complemento");

        jLabel4.setText("Bairro");

        jLabel5.setText("Numero");

        jLabel6.setText("Telefone");

        jLabel7.setText("CNPJ");

        jLabel8.setText("Inscrição");

        jLabel9.setText("Estado");

        jLabel10.setText("Cidade");

        jtxtcomp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtcompActionPerformed(evt);
            }
        });

        jLabel11.setText("Email");

        jestados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estados:", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO", " " }));

        jempresas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Endereço", "Complemento", "Bairro", "Numero", "Cidade", "Estado", "CNPJ", "Inscrição Estadual", "Telefone", "Email"
            }
        ));
        jScrollPane1.setViewportView(jempresas);

        jLabel12.setText("ID");

        jbtnadd.setBackground(new java.awt.Color(51, 255, 51));
        jbtnadd.setText("Inserir Empresa");
        jbtnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnaddActionPerformed(evt);
            }
        });

        jbtnexcludeone.setBackground(new java.awt.Color(255, 0, 0));
        jbtnexcludeone.setText("Excluir Empresa");
        jbtnexcludeone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnexcludeoneActionPerformed(evt);
            }
        });

        jbtnexcludeall.setBackground(new java.awt.Color(255, 0, 0));
        jbtnexcludeall.setText("Excluir todas as empresas");
        jbtnexcludeall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnexcludeallActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setText("Sair");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jtxtnome, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jtxtend, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtcomp, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxtbairro, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jnum, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbtnexcludeall, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnexcludeone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnadd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(122, 122, 122))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jcidade, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jinscricao, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jcnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jestados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(14, 14, 14)
                                        .addComponent(jtelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(143, 143, 143)
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jtxtid, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(10, 10, 10)
                                        .addComponent(jemail, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 968, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtxtnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)
                        .addComponent(jtxtend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtxtcomp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtxtbairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtnadd))
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jcidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jestados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(jemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnexcludeall)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jinscricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel12)
                                .addComponent(jtxtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jbtnexcludeone))
                        .addGap(20, 20, 20)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(44, 44, 44))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtcompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtcompActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtcompActionPerformed

    private void jtxtnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtnomeActionPerformed

    private void jbtnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnaddActionPerformed
        controller.salvaVendedor();
        try {
            readJtable();
        } catch (SQLException ex) {
            Logger.getLogger(CadastroEmpresa.class.getName()).log(Level.SEVERE, null, ex);
        }
        jtxtnome.setText("");
        jtxtbairro.setText("");
        jtxtcomp.setText("");
        jtxtend.setText("");
        jinscricao.setText("");
        jnum.setText("");
        jtelefone.setText("");
        jcnpj.setText("");
        jemail.setText("");
        jcidade.setText("");
        
    }//GEN-LAST:event_jbtnaddActionPerformed

    private void jbtnexcludeallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnexcludeallActionPerformed
        controller.excluitudo();
        try {
            readJtable();
        } catch (SQLException ex) {
            Logger.getLogger(CadastroEmpresa.class.getName()).log(Level.SEVERE, null, ex);
        }
        jtxtid.setText("");
        jtxtnome.setText("");
        jtxtbairro.setText("");
        jtxtcomp.setText("");
        jtxtend.setText("");
        jinscricao.setText("");
        jnum.setText("");
        jtelefone.setText("");
        jcnpj.setText("");
        jemail.setText("");
        jcidade.setText("");
    }//GEN-LAST:event_jbtnexcludeallActionPerformed

    private void jbtnexcludeoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnexcludeoneActionPerformed
        controller.excluiUM();
        try {
            readJtable();
        } catch (SQLException ex) {
            Logger.getLogger(CadastroEmpresa.class.getName()).log(Level.SEVERE, null, ex);
        }
        jtxtnome.setText("");
        jtxtbairro.setText("");
        jtxtcomp.setText("");
        jtxtend.setText("");
        jinscricao.setText("");
        jnum.setText("");
        jtelefone.setText("");
        jcnpj.setText("");
        jemail.setText("");
        jcidade.setText("");
        jtxtid.setText("");
    }//GEN-LAST:event_jbtnexcludeoneActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new CadastroEmpresa().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(CadastroEmpresa.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    public JTextField getJcidade() {
        return jcidade;
    }

    public void setJcidade(JTextField jcidade) {
        this.jcidade = jcidade;
    }

    public JFormattedTextField getJcnpj() {
        return jcnpj;
    }

    public void setJcnpj(JFormattedTextField jcnpj) {
        this.jcnpj = jcnpj;
    }

    public JTextField getJemail() {
        return jemail;
    }

    public void setJemail(JTextField jemail) {
        this.jemail = jemail;
    }

    public JComboBox<String> getJestados() {
        return jestados;
    }

    public void setJestados(JComboBox<String> jestados) {
        this.jestados = jestados;
    }

    public JFormattedTextField getJinscricao() {
        return jinscricao;
    }

    public void setJinscricao(JFormattedTextField jinscricao) {
        this.jinscricao = jinscricao;
    }

    public JTextField getJnum() {
        return jnum;
    }

    public void setJnum(JTextField jnum) {
        this.jnum = jnum;
    }

    public JFormattedTextField getJtelefone() {
        return jtelefone;
    }

    public void setJtelefone(JFormattedTextField jtelefone) {
        this.jtelefone = jtelefone;
    }

    public JTextField getJtxtbairro() {
        return jtxtbairro;
    }

    public void setJtxtbairro(JTextField jtxtbairro) {
        this.jtxtbairro = jtxtbairro;
    }

    public JTextField getJtxtcomp() {
        return jtxtcomp;
    }

    public void setJtxtcomp(JTextField jtxtcomp) {
        this.jtxtcomp = jtxtcomp;
    }

    public JTextField getJtxtend() {
        return jtxtend;
    }

    public void setJtxtend(JTextField jtxtend) {
        this.jtxtend = jtxtend;
    }

    public JTextField getJtxtid() {
        return jtxtid;
    }

    public void setJtxtid(JTextField jtxtid) {
        this.jtxtid = jtxtid;
    }

    public JTextField getJtxtnome() {
        return jtxtnome;
    }

    public void setJtxtnome(JTextField jtxtnome) {
        this.jtxtnome = jtxtnome;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnadd;
    private javax.swing.JButton jbtnexcludeall;
    private javax.swing.JButton jbtnexcludeone;
    private javax.swing.JTextField jcidade;
    private javax.swing.JFormattedTextField jcnpj;
    private javax.swing.JTextField jemail;
    private javax.swing.JTable jempresas;
    private javax.swing.JComboBox<String> jestados;
    private javax.swing.JFormattedTextField jinscricao;
    private javax.swing.JTextField jnum;
    private javax.swing.JFormattedTextField jtelefone;
    private javax.swing.JTextField jtxtbairro;
    private javax.swing.JTextField jtxtcomp;
    private javax.swing.JTextField jtxtend;
    private javax.swing.JTextField jtxtid;
    private javax.swing.JTextField jtxtnome;
    // End of variables declaration//GEN-END:variables
}
